config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'
  resources :posts , only: [:show, :index]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'

    namespace :admin do
        resources :posts, except: [:show, :index]

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title, :summary, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
before_action :authenticate_user!
before_action :set_post, only: [:show, :edit, :update, :destroy]


  def new
    @post = Post.new
  end
  def create
  #render plain: params[:post].inspect
   @post = Post.new(post_params)
  if (@post.save)
   redirect_to [:admin,@post], success: 'Статья успешно создана'
 else
   flash[:danger] = 'Статья не создана'
   render 'new'
 end
  end

  private def post_params
    params.require(:post).permit(:title, :body , :summary, :image)
  end
  def edit

end
def update

  if @post.update(post_params)
   redirect_to [:admin,@post], success: 'Статья успешно обновлена'
 else
   flash[:danger] = 'Статья не обновлена'

   render 'edit'
 end
end
def destroy
@post.destroy
redirect_to posts_path, success: 'Статья успешно удалена'
end
private
def set_post
@post = Post.find(params[:id])
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show

  def index
    @posts = Post.all
  end

  def show
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_breadcrumb(category)
    result = []
    category.ancestors.each do |ancestor|
      result << content_tag(:li, class: "breadcrumb-item") do
        link_to(ancestor.name, ancestor)
      end
    end
    result << content_tag(:li, category.name, class: "breadcrumb-item active")
    result.join('').html_safe
  end

  def bootstrap_class_for(name)
    { success:"alert-success",
      error:  "alert-danger",
      danger: "alert-danger",
      alert:  "alert-warning",
      notice: "alert-info"
    }[name.to_sym] || name
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/admin/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors')%></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @post], html: { multipart: true } do |f| %>
<div class="form-group">
<%= f.label :title %>
<%= f.text_field :title, class: 'form-control'%>
</div>
<div class="form-group">
<%= f.label :summary %>
<%= f.text_area :summary, class: 'form-control'%>
</div>
<div class="form-group">
<%= f.label :body %>
<%= f.text_area :body, class: 'form-control'%>
</div>

<div class="form-group">
<%= f.file_field :image %>
</div>

<br>
<div class="form-group">
<%= f.submit 'Coxpaнить', class: 'btn btn-primary' %>
<%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
</div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Редактирование статьи</h1>

<%= render 'form' %>

app/views/admin/posts/new.html.erb
<h1>новая статья</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container ">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="<%= posts_path%>">Статьи</a>
              </li>

<% if user_signed_in? %>
              <%= link_to 'Новая статья', new_admin_post_path, class: 'btn btn-outline-primary'%>
 <% end %>
                <ul class="navbar-nav pull-xs-right">
                 <% if user_signed_in? %>
                   <li class="nav-item">
                     <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
                   </li>
                 <% else %>
                   <li class="nav-item">
                     <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
                   </li>
                   <li class="nav-item">
                     <%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %>
                   </li>
                 <% end %>

               </ul>
            </div>
          </div>
        </nav>
      </div>

      <div class="container main">
        <div class="row">
          <div class="col-md-12">
          <% flash.each do |name, message| %>
        <div class="alert <%= bootstrap_class_for(name) %>">
          <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
            </div>
          <% end %>
          </div>
        </div>
        <%= yield %>
      </div>

    </body>
  </html>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
       <% if user_signed_in?%>
      |
      <%= link_to 'Изменить', edit_admin_post_path(post) %>
      |
      <%= link_to 'Удалить', admin_post_path(post), method: :delete, data: { confirm: 'Ви уверени?'} %>
        <% end %>
    </small>
  </section>
  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>
</article>

app/views/posts/index.html.erb
<h1>Статьи</h1>
<%= render @posts %>

app/views/posts/show.html.erb
<article class="post">
  <section class="post-head">
    <h1><%=  @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if user_signed_in? %>
      |
      <%= link_to 'Изменить', edit_admin_post_path(@post) %>
      |
      <%= link_to 'Удалить', admin_post_path(@post), method: :delete, data: { confirm: 'Ви уверени?'} %>
        <% end %>
    </small>
  </section>
  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.body.html_safe %>
  </section>
  </article>